version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[global]"
    labels:
      - "⚙ Setting"
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "io.spring.dependency-management"
        update-types:
          - "minor"
          - "patch"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
        update-types:
          - "minor"
          - "patch"
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "[global]"
    labels:
      - "⚙ Setting"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "[ci/cd]"
    labels:
      - "⚙ Setting"
    groups:
      github-actions:
        patterns:
          - "*"
