services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gsmc-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7-alpine
    container_name: gsmc-redis
    restart: always
    command: ["redis-server", "--requirepass", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: