type Evidence {
    evidenceId: ID!
    userId: ID!
    evidenceTitle: String
    evidenceContent: String
    evidenceCreatedAt: DateTime
    evidenceUpdatedAt: DateTime
    files: [File!]!
}

input CreateEvidenceInput {
    scoreId: ID!
    title: String!
    content: String!
    fileIds: [ID!] = []
}

input PatchEvidenceInput {
    scoreId: ID
    title: String
    content: String
    fileIds: [ID!]
}

input CreateEvidenceDraftInput {
    title: String = ""
    content: String = ""
    fileIds: [ID!] = []
}
