name: CD

on:
  push:
    branches:
      - main
      - develop
      - feat/cicd
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build backend
        run: ./gradlew build -x test     
      
      - name: run Ktlint
        run: ./gradlew ktlintCheck

      - name: Deploy backend
        uses: appleboy/ssh-action@v1
        with:
          username: ubuntu
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/GSMC-server-V4
            git pull origin develop
            sudo docker compose down
            sudo docker compose up -d --build